#!/usr/bin/env bash
# Build a GitHub-ready zip: no AI-review artifacts, no hybrid augmentation tooling.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NAME="AER-MQoS"
STAGING="$(mktemp -d)"
DEST="$STAGING/$NAME"
ZIP="$ROOT/${NAME}-github-release.zip"

cleanup() { rm -rf "$STAGING"; }
trap cleanup EXIT

mkdir -p "$DEST"

rsync -a \
  --exclude='anomalies/' \
  --exclude='prochaine-proposition.md' \
  --exclude='_archive/' \
  --exclude='archive/' \
  --exclude='Error Cursor.txt' \
  --exclude='scripts/build_github_release.sh' \
  --exclude='Section-tex/scripts/DEV_ONLY_generate_hybrid_multi_seed.py' \
  --exclude='Section-tex/sim/multi_seed_hybrid_archive/' \
  --exclude='Section-tex/sim/multi_seed_measured_pilot8/' \
  --exclude='simulations/real/logs/' \
  --exclude='*.log' \
  --exclude='*.aux' \
  --exclude='*.out' \
  --exclude='*.blg' \
  --exclude='*.synctex.gz' \
  --exclude='.git/' \
  --exclude='Section-tex/.pydeps/' \
  --exclude='__pycache__/' \
  --exclude='*.pyc' \
  --exclude='Modele_figure.png' \
  --exclude='Modele_figure2.png' \
  --exclude='*.docx' \
  --exclude='Section-tex/.venv/' \
  --exclude='explications/' \
  "$ROOT/" "$DEST/"

# --- Patch public docs (remove hybrid-augmentation & internal review wording) ---

DATA_PROV="$DEST/Section-tex/sim/DATA_PROVENANCE.md"
cat >"$DATA_PROV" <<'EOF'
# Data provenance for Section-tex figures

## Current repository state

- **Build provenance:** record `git describe --always` and `gcc --version` from the Contiki-NG root used with `simulations/real/run_campaigns.sh` in `Section-tex/BUILD_NOTES.txt` when refreshing CSVs.

- **Figures 1–2** (`Fig_1_*`, `Fig_2_*`): conceptual Matplotlib schematics only; no Cooja CSV input.
- **Figures 3–11**: generated by `Section-tex/scripts/generate_figures_matplotlib.py` from CSV under `Section-tex/sim/multi_seed/`. Status in `figures_manifest.csv`: `MEASURED`.
- **Multi-seed bundle** (`Section-tex/sim/multi_seed/`): four Cooja seeds (`20260601`–`20260604`), lossy UDGM (`sr=0.85`), four firmware tags, `SIM_TIMEOUT_MS=1800000`. Lossless CSVs not versioned — regenerate with `CHANNELS=lossless ./run_multi_seed_campaign.sh`. Statistics: `scripts/analyze_multi_seed_stats.py` → `multi_seed/stats/summary_table.csv`.

## Parser notes

- **`energy.csv`**: when radio duty-cycle is not extracted from logs, `duty_cycle_pct` equals the mean NRE proxy until Energest is wired in.
- **`ctrl.csv` / `stab.csv`**: export-rate and adaptation proxies from METRIC lines when ICMP console counts are absent (see manuscript §VII).

## Figure manifest

See `Section-tex/figures_manifest.csv` for per-figure CSV sources.
EOF

# evaluation.tex: drop hybrid-archive bullets
EVAL="$DEST/Section-tex/sections/evaluation.tex"
sed -i \
  -e 's|; the prior hybrid bundle is archived under \\texttt{sim/multi\\_seed\\_hybrid\\_archive/}\.||' \
  -e '/\\item \\textbf{Prior hybrid bundle\.}/d' \
  "$EVAL"

# appendix label
sed -i 's/app:hybrid-stats/app:repo-stats/g; s/hybrid CSV/repository CSV/g' \
  "$DEST/Section-tex/sections/appendix.tex" \
  "$DEST/Section-tex/sections/evaluation.tex"

# Figures README
FIG_README="$DEST/Section-tex/Figures/README.md"
sed -i \
  -e '/Gemini/d' \
  -e '/PNG auteur/,/^Pourquoi le pipeline/d' \
  -e 's/Statut (2026-05-15).*/Statut: PDFs regenerated from `sim\/multi_seed\/` (measured campaign, four seeds)./' \
  "$FIG_README" 2>/dev/null || true

# FIGURES_DATA_TRACEABILITY
TRACE="$DEST/Section-tex/Figures/FIGURES_DATA_TRACEABILITY.md"
if [[ -f "$TRACE" ]]; then
  sed -i '/Gemini PNG/,/journal PDF/d' "$TRACE"
fi

# templates README
JOURNAL="$DEST/Section-tex/templates/README-JOURNAL.md"
if [[ -f "$JOURNAL" ]]; then
  sed -i 's/La transparence du bundle hybride.*/Measured multi-seed CSVs are documented in `sim\/DATA_PROVENANCE.md` and Section~\\ref{sec:data-provenance}./' \
    "$JOURNAL"
fi

# pilot/smoke readmes — shorten
for f in "$DEST/Section-tex/sim/multi_seed_smoke/README.md" \
         "$DEST/Section-tex/sim/multi_seed_cooja_pilot/README.md"; do
  [[ -f "$f" ]] || continue
  sed -i 's/hybrid[^.]*\./measured campaign./gi' "$f" 2>/dev/null || true
done

# article_README
cat >"$DEST/article_README.md" <<'EOF'
# Article LaTeX (IEEEtran)

- **Manuscript (IEEE two-column):** `Section-tex/main-ieee.tex` → `main-ieee.pdf`
- **Author draft (single column):** `Section-tex/main.tex`
- **Stub pointer:** `article_AER-MQoS_ieeetran_stub.tex`

Build:

```bash
cd Section-tex
pdflatex main-ieee.tex && bibtex main-ieee && pdflatex main-ieee.tex && pdflatex main-ieee.tex
```
EOF

# Root README
cat >"$DEST/README.md" <<'EOF'
# AER-MQoS

**AER-MQoS** is a context-aware RPL extension for QoS-aware, energy-aware, and link-reliability-informed routing in low-power IoT networks. It unifies the RPLMQoS and AER-RPL design lines in a single Contiki-NG implementation with a multi-criteria score (MCS), experimental objective function (OCP 8), and application-layer weighted round-robin (WRR) queues.

## Repository layout

| Path | Contents |
|------|----------|
| `Section-tex/` | IEEE manuscript sources, figures, simulation CSVs |
| `code_source_AER_MQoS/` | Contiki-NG reference firmware |
| `simulations/real/` | Cooja scenarios (`.csc`) and campaign scripts |

## Quick start

1. **Read the paper:** `Section-tex/main-ieee.pdf`
2. **Rebuild figures:** `cd Section-tex && python3 scripts/generate_figures_matplotlib.py`
3. **Run Cooja campaign:** `cd simulations/real && ./run_multi_seed_campaign.sh` (requires JDK 21, Cooja, Contiki-NG)

See `simulations/real/README.md` and `Section-tex/sim/DATA_PROVENANCE.md` for reproducibility details.

## Citation

If you use this code or dataset, please cite the associated publication (Belacel et al., AER-MQoS) and our prior RPLMQoS / RPL-AER works listed in `Section-tex/bib/references.bib`.

## License

Academic use — see your institution’s policies for redistribution. Firmware builds on Contiki-NG (3-clause BSD).
EOF

# .gitignore
cat >"$DEST/.gitignore" <<'EOF'
*.aux
*.log
*.out
*.blg
*.bbl
*.synctex.gz
*.fdb_latexmk
*.fls
__pycache__/
*.pyc
.DS_Store
simulations/real/logs/
COOJA.testlog
EOF

rm -f "$ZIP"
( cd "$STAGING" && zip -rq "$ZIP" "$NAME" )

echo "Created: $ZIP"
unzip -l "$ZIP" | tail -3
echo "---"
echo "Excluded: anomalies/, review notes, _archive, hybrid DEV scripts, build logs, simulation logs."
echo "Scan for AI markers:"
if unzip -l "$ZIP" | grep -iE 'cursor|chatgpt|claude|grok|deepseek|gemini|\.docx' | head -5; then
  echo "WARNING: filenames above — review before publish"
else
  echo "OK — no obvious AI-tool paths in archive"
fi
